services:
  backend:
    build:
      context: ./pricing_tool_backend
      dockerfile: Dockerfile
    volumes:
      - ./pricing_tool_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./pricing_tool_frontend
      dockerfile: Dockerfile
    volumes:
      - ./pricing_tool_frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pricing_tool_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - .env

    ports:
      - "5432:5432"

volumes:
  postgres_data:
