# Generated by Django 4.2.5 on 2025-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('stock_available', models.IntegerField()),
                ('units_sold', models.IntegerField()),
                ('customer_rating', models.IntegerField()),
                ('demand_forecast', models.IntegerField()),
                ('optimized_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
