import manage_product from "@/assets/manage_product.png";
import price_optimization from "@/assets/price_optimization.png";
import { Product } from "@/types/types";

const CardData = [
  {
    title: "Create and Manage Product",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua.",
    link: "/manage-product",
    icon: manage_product,
  },
  {
    title: "Price Optimization",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua.",
    link: "/price-optimization",
    icon: price_optimization,
  },
];

const Products: Product[] = [
  {
    id: 1,
    name: "Eco-Friendly Water Bottle",
    description:
      "A sustainable, reusable water bottle made from recycled materials.",
    cost_price: "5.00",
    selling_price: "12.99",
    category: "Outdoor & Sports",
    stock_available: 500,
    units_sold: 200,
    customer_rating: 4,
    demand_forecast: 250,
    optimized_price: "11.50",
  },
  {
    id: 2,
    name: "Wireless Earbuds",
    description:
      "Bluetooth 5.0 wireless earbuds with noise cancellation and long battery life.",
    cost_price: "25.00",
    selling_price: "59.99",
    category: "Electronics",
    stock_available: 300,
    units_sold: 150,
    customer_rating: 5,
    demand_forecast: 180,
    optimized_price: "55.00",
  },
  {
    id: 3,
    name: "Organic Cotton T-Shirt",
    description: "Soft, breathable t-shirt made from 100% organic cotton.",
    cost_price: "8.00",
    selling_price: "19.99",
    category: "Apparel",
    stock_available: 400,
    units_sold: 100,
    customer_rating: 4,
    demand_forecast: 120,
    optimized_price: "18.50",
  },
  {
    id: 4,
    name: "Smart Home Hub",
    description: "Control all your smart home devices with this central hub.",
    cost_price: "40.00",
    selling_price: "99.99",
    category: "Home Automation",
    stock_available: 150,
    units_sold: 75,
    customer_rating: 4,
    demand_forecast: 90,
    optimized_price: "95.00",
  },
  {
    id: 5,
    name: "Electric Scooter",
    description: "Lightweight electric scooter with a range of 20 miles.",
    cost_price: "150.00",
    selling_price: "299.99",
    category: "Transportation",
    stock_available: 80,
    units_sold: 40,
    customer_rating: 5,
    demand_forecast: 50,
    optimized_price: "285.00",
  },
  {
    id: 6,
    name: "Noise-Canceling Headphones",
    description: "Over-ear headphones with active noise cancellation.",
    cost_price: "50.00",
    selling_price: "129.99",
    category: "Electronics",
    stock_available: 200,
    units_sold: 90,
    customer_rating: 4,
    demand_forecast: 110,
    optimized_price: "125.00",
  },
  {
    id: 7,
    name: "Smartwatch",
    description: "Feature-packed smartwatch with heart rate monitor and GPS.",
    cost_price: "70.00",
    selling_price: "149.99",
    category: "Wearables",
    stock_available: 250,
    units_sold: 130,
    customer_rating: 5,
    demand_forecast: 160,
    optimized_price: "145.00",
  },
  {
    id: 8,
    name: "Portable Solar Charger",
    description: "Compact solar charger for outdoor use.",
    cost_price: "20.00",
    selling_price: "39.99",
    category: "Outdoor & Sports",
    stock_available: 300,
    units_sold: 140,
    customer_rating: 4,
    demand_forecast: 170,
    optimized_price: "38.00",
  },
  {
    id: 9,
    name: "Fitness Tracker",
    description: "Wearable fitness tracker with sleep monitoring.",
    cost_price: "30.00",
    selling_price: "59.99",
    category: "Wearables",
    stock_available: 350,
    units_sold: 180,
    customer_rating: 4,
    demand_forecast: 200,
    optimized_price: "57.00",
  },
  {
    id: 10,
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with excellent sound quality.",
    cost_price: "15.00",
    selling_price: "45.99",
    category: "Electronics",
    stock_available: 400,
    units_sold: 210,
    customer_rating: 4,
    demand_forecast: 240,
    optimized_price: "43.00",
  },
];
export { CardData, Products };
